export // List of famous companies
const famousCompanyList = [
  "20th Century Studios",
  "DreamWorks",
  "Amazon MGM Studios",
  "Marvel Studios",
  "Paramount Pictures",
  "Sony Pictures",
  "Universal Pictures",
  "Walt Disney Studios",
  "Warner Bros.",
  "Netflix",
  "Lionsgate",
  "Columbia Pictures"
];

export const productionCompanies = [
  "20th Century Studios",
  "A24",
  "ABC Studios",
  "Amazon MGM Studios",
  "Apple TV+",
  "Ardavan Productions",
  "Atlas Entertainment",
  "Bac Films",
  "Bad Robot Productions",
  "BBC Studios",
  "Beijing Enlight Pictures",
  "Blumhouse Productions",
  "Bold Films",
  "Bona Film Group",
  "Canal+",
  "Caracol Televisión",
  "Castle Rock Entertainment",
  "Chesler/Perlmutter Productions",
  "China Film Group Corporation",
  "Columbia Pictures",
  "Conaco",
  "Coriolanus Productions",
  "Davis Entertainment",
  "DreamWorks",
  "Eagle Pictures",
  "Endemol Shine Group",
  "Entertainment One",
  "Fremantle",
  "Gaga Communications",
  "Gaumont",
  "Ghibli Museum",
  "Glenwood Media",
  "Granada Television",
  "Hanna-Barbera Productions",
  "HBO",
  "Hulu",
  "Icon Productions",
  "Illumination Entertainment",
  "Imperative Entertainment",
  "Interscope Communications",
  "ITV Studios",
  "J.J. Abrams Productions",
  "Lionsgate",
  "Luma Pictures",
  "Marvel Studios",
  "Metro-Goldwyn-Mayer",
  "Miramax",
  "MRC",
  "National Geographic Studios",
  "New Line Cinema",
  "Netflix",
  "Nippon TV",
  "Nora Ephron Productions",
  "Orion Pictures",
  "Paramount Pictures",
  "Pathé",
  "Pearl Studio",
  "Platinum Dunes",
  "Polaris Productions",
  "PolyGram Filmed Entertainment",
  "Rogue Pictures",
  "Rupert Murdoch Productions",
  "Saban Films",
  "Scott Free Productions",
  "Sony Pictures",
  "Studio Ghibli",
  "Studio 8",
  "Sony Pictures Animation",
  "Starz",
  "Syfy",
  "Televisa",
  "The Asylum",
  "The Weinstein Company",
  "Toho Company",
  "Toonzone Studios",
  "Trancas International Films",
  "TriStar Pictures",
  "Universal Pictures",
  "Valhalla Entertainment",
  "Village Roadshow Pictures",
  "Walt Disney Studios",
  "Warner Bros.",
  "Wild Bunch",
  "Working Title Films",
  "Zeta Cinema",
  "Aardman Animations",
  "Aerie Films",
  "Annapurna Pictures",
  "Arcade Pictures",
  "Ardmore Studios",
  "Babelsberg Film Studio",
  "Baker & Baker Productions",
  "Barunson E&A",
  "Beelink Films",
  "Big Talk Productions",
  "Blue Sky Studios",
  "Boomerang Films",
  "Boulevard Productions",
  "Bridges Media",
  "Broccoli Productions",
  "Cineworld",
  "Cloud 9 Productions",
  "Coen Brothers Productions",
  "Concordia Films",
  "Cosmos Studios",
  "Darlow Smithson Productions",
  "Daybreak Pictures",
  "Deluxe Entertainment",
  "Desperate Pictures",
  "Di Bonaventura Pictures",
  "Discovery Channel",
  "Dynamite Entertainment",
  "Entertainment Studios",
  "Epic Pictures",
  "Fable Pictures",
  "Falcon Pictures",
  "Film Nation Entertainment",
  "Film4 Productions",
  "Giant Pictures",
  "Gold Circle Films",
  "Good Universe",
  "Greenwich Entertainment",
  "Groundswell Productions",
  "H2O Productions",
  "Harrison Films",
  "Hershey Films",
  "Hoopla Productions",
  "Hypnotic Films",
  "Iconoclast",
  "Indian Paintbrush",
  "Ingenious Media",
  "International Pictures",
  "Jive Media",
  "Kaleidoscope Film Distribution",
  "Karma Films",
  "Kopelson Entertainment",
  "Lakeshore Entertainment",
  "Laika Entertainment",
  "Lions Gate Entertainment",
  "Lucky 8 Productions",
  "Mamma Mia Productions",
  "Manhattan Productions",
  "Metropolis Films",
  "Mighty Media",
  "Modern Films",
  "Moonlight Films",
  "Mosaic Media Group",
  "New Regency",
  "Northwood Productions",
  "Octagon Films",
  "Omega Productions",
  "Opus Pictures",
  "Overture Films",
  "Paloma Productions",
  "Passion Pictures",
  "Pinewood Studios",
  "Pinnacle Films",
  "Premiere Pictures",
  "Raging Bull Productions",
  "Red Granite Pictures",
  "Rising Star Productions",
  "Rough House Pictures",
  "Saboteur Productions",
  "Santos Productions",
  "Sierra Pictures",
  "Silver Pictures",
  "Skyline Productions",
  "Sola Media",
  "Sundance Productions",
  "Sunset Pictures",
  "Tagline Productions",
  "The Alliance Films",
  "The Imaginarium",
  "The Ink Factory",
  "The Little Film Company",
  "The Masked Films",
  "The Samaritans",
  "The Storyteller Productions",
  "Thunder Road Pictures",
  "Titan Films",
  "Tommy Boy Films",
  "Top Hat Productions",
  "TriStar Pictures",
  "True North Productions",
  "United Artists",
  "Vanguard Films",
  "Viking Studios",
  "Weinstein Company",
  "WestEnd Films",
  "Wishing Tree Productions",
  "Yellowstone Films",
  "Zephyr Films",
  "Zodiac Pictures"
];
